name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Ensure latest npm version
        run: npm install -g npm

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Test
        run: npm run test
        env:
          NODE_ENV: test
          CI: true
